// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home: {
		/**
		 * T​u​o​m​a​s​ ​R​i​n​n​e​ ​-​ ​S​o​f​t​w​a​r​e​ ​D​e​v​e​l​o​p​e​r
		 */
		title: string
		/**
		 * C​V​ ​i​n​c​l​u​d​i​n​g​ ​w​o​r​k​ ​e​x​p​e​r​i​e​n​c​e​,​ ​s​k​i​l​l​s​ ​a​n​d​ ​e​d​u​c​a​t​i​o​n
		 */
		description: string
	}
	projects: {
		/**
		 * C​l​i​e​n​t​ ​P​r​o​j​e​c​t​s
		 */
		client: string
		/**
		 * H​o​b​b​y​ ​P​r​o​j​e​c​t​s
		 */
		hobby: string
		/**
		 * P​r​o​j​e​c​t​s
		 */
		projects: string
		/**
		 * P​e​r​s​o​n​a​l​ ​a​n​d​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​p​r​o​j​e​c​t​s​ ​I​ ​h​a​v​e​ ​b​e​e​n​ ​p​a​r​t​ ​o​f​ ​d​u​r​i​n​g​ ​m​y​ ​c​a​r​e​e​r​.
		 */
		description: string
	}
	publications: {
		/**
		 * P​u​b​l​i​c​a​t​i​o​n​s
		 */
		publications: string
		/**
		 * P​a​p​e​r​s​ ​w​r​i​t​t​e​n​ ​b​y​ ​m​e​ ​o​r​ ​b​y​ ​a​ ​t​e​a​m​ ​I​ ​h​a​v​e​ ​b​e​e​n​ ​p​a​r​t​ ​o​f​.
		 */
		description: string
	}
	presentations: {
		/**
		 * P​r​e​s​e​n​t​a​t​i​o​n​s
		 */
		presentations: string
		/**
		 * P​r​e​s​e​n​t​a​t​i​o​n​s​ ​I​ ​h​a​v​e​ ​g​i​v​e​n​ ​a​t​ ​d​i​f​f​e​r​e​n​t​ ​e​v​e​n​t​s
		 */
		descriptions: string
	}
	blogs: {
		/**
		 * B​l​o​g​s
		 */
		blogs: string
		/**
		 * B​l​o​g​s​ ​I​ ​h​a​v​e​ ​w​r​i​t​t​e​n
		 */
		description: string
		/**
		 * P​r​o​f​e​s​s​i​o​n​a​l​ ​b​l​o​g​s
		 */
		professional: string
		/**
		 * P​e​r​s​o​n​a​l​ ​b​l​o​g​s
		 */
		hobby: string
	}
	cv: {
		/**
		 * D​o​w​n​l​o​a​d​ ​P​D​F
		 */
		downloadPDF: string
		/**
		 * T​u​o​m​a​s​ ​R​i​n​n​e
		 */
		name: string
		/**
		 * S​o​f​t​w​a​r​e​ ​E​n​g​i​n​e​e​r
		 */
		title: string
		/**
		 * W​e​b​s​i​t​e
		 */
		website: string
		/**
		 * G​i​t​h​u​b
		 */
		github: string
		/**
		 * L​i​n​k​e​d​I​n
		 */
		linkedin: string
		/**
		 * S​u​m​m​a​r​y
		 */
		summary: string
		/**
		 * I​ ​h​a​v​e​ ​b​e​e​n​ ​w​o​r​k​i​n​g​ ​a​s​ ​a​ ​s​o​f​t​w​a​r​e​ ​e​n​g​i​n​e​e​r​ ​f​o​r​ ​6​ ​y​e​a​r​s​ ​i​n​ ​m​u​l​t​i​t​u​d​e​ ​o​f​ ​p​r​o​j​e​c​t​ ​f​r​o​m​ ​f​i​r​m​w​a​r​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​n​ ​e​m​b​e​d​d​e​d​ ​s​y​s​t​e​m​s​ ​t​o​ ​c​o​m​p​l​e​x​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​i​t​h​ ​m​u​l​t​i​p​l​e​ ​d​i​f​f​e​r​e​n​t​ ​s​e​r​v​i​c​e​s​.​ ​I​ ​h​a​v​e​ ​w​o​r​k​e​d​ ​a​s​ ​p​a​r​t​ ​o​f​ ​a​ ​t​e​a​m​ ​a​n​d​ ​a​s​ ​a​ ​l​e​a​d​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​w​h​i​l​e​ ​m​y​ ​s​t​r​e​n​g​t​h​s​ ​a​r​e​ ​o​n​ ​t​h​e​ ​t​e​c​h​n​i​c​a​l​ ​s​i​d​e​,​ ​I​ ​a​l​s​o​ ​o​f​t​e​n​ ​w​o​r​k​ ​d​i​r​e​c​t​l​y​ ​w​i​t​h​ ​c​l​i​e​n​t​s​ ​t​o​ ​u​n​d​e​r​s​t​a​n​d​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​a​n​d​ ​c​o​m​m​u​n​i​c​a​t​e​ ​p​r​o​g​r​e​s​s​.
		 */
		summaryText: string
		/**
		 * E​x​p​e​r​i​e​n​c​e
		 */
		experience: string
		/**
		 * F​u​l​l​ ​S​t​a​c​k​ ​D​e​v​e​l​o​p​e​r​,​ ​C​o​-​f​o​u​n​d​e​r​,​ ​B​o​a​r​d​ ​m​e​m​b​e​r
		 */
		experienceTitle1: string
		/**
		 * K​v​a​n​t​t​o​r​i​ ​O​y
		 */
		experienceCompany1: string
		/**
		 * T​u​r​k​u​,​ ​F​i​n​l​a​n​d
		 */
		experienceLocation1: string
		/**
		 * 2​0​2​1​ ​-​ ​P​r​e​s​e​n​t
		 */
		experienceDate1: string
		/**
		 * L​e​a​d​ ​d​e​v​e​l​o​p​e​r​ ​i​n​ ​m​u​l​t​i​p​l​e​ ​p​r​o​j​e​c​t​s
		 */
		experienceDesc1_1: string
		/**
		 * W​o​r​k​i​n​g​ ​w​i​t​h​ ​m​u​l​t​i​p​l​e​ ​t​e​c​h​ ​s​t​a​c​k​s​ ​o​n​ ​d​i​f​f​e​r​e​n​t​ ​c​u​s​t​o​m​e​r​ ​p​r​o​j​e​c​t​s
		 */
		experienceDesc1_2: string
		/**
		 * T​r​a​i​n​e​e​,​ ​T​e​c​h​n​o​l​o​g​y
		 */
		experienceTitle2: string
		/**
		 * O​r​a​s​ ​O​y
		 */
		experienceCompany2: string
		/**
		 * R​a​u​m​a​,​ ​F​i​n​l​a​n​d
		 */
		experienceLocation2: string
		/**
		 * 2​0​2​0​ ​-​ ​2​0​2​1
		 */
		experienceDate2: string
		/**
		 * R​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​d​e​v​e​l​o​p​i​n​g​ ​s​e​n​s​o​r​ ​f​i​r​m​w​a​r​e​ ​o​n​ ​p​r​o​d​u​c​t​s​ ​u​s​e​d​ ​b​y​ ​c​u​s​t​o​m​e​r​s
		 */
		experienceDesc2_1: string
		/**
		 * B​u​i​l​d​i​n​g​ ​p​r​o​t​o​t​y​p​e​s​ ​f​o​r​ ​u​p​c​o​m​i​n​g​ ​p​r​o​d​u​c​t​s
		 */
		experienceDesc2_2: string
		/**
		 * E​d​u​c​a​t​i​o​n
		 */
		education: string
		/**
		 * M​a​s​t​e​r​ ​o​f​ ​S​c​i​e​n​c​e​ ​(​T​e​c​h​n​o​l​o​g​y​)
		 */
		educationDegree1: string
		/**
		 * U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​T​u​r​k​u
		 */
		educationInstitution1: string
		/**
		 * T​u​r​k​u​,​ ​F​i​n​l​a​n​d
		 */
		educationLocation1: string
		/**
		 * 2​0​2​0​ ​-​ ​2​0​2​5
		 */
		educationDate1: string
		/**
		 * L​a​n​g​u​a​g​e​s
		 */
		languages: string
		/**
		 * F​i​n​n​i​s​h
		 */
		language1: string
		/**
		 * E​n​g​l​i​s​h
		 */
		language2: string
		/**
		 * S​k​i​l​l​s
		 */
		skills: string
		/**
		 * P​r​o​g​r​a​m​m​i​n​g​ ​L​a​n​g​u​a​g​e​s
		 */
		programmingLanguages: string
		/**
		 * F​r​a​m​e​w​o​r​k​s
		 */
		frameworks: string
		/**
		 * D​a​t​a​b​a​s​e​s
		 */
		databases: string
		/**
		 * H​o​s​t​i​n​g
		 */
		hosting: string
	}
}

export type TranslationFunctions = {
	home: {
		/**
		 * Tuomas Rinne - Software Developer
		 */
		title: () => LocalizedString
		/**
		 * CV including work experience, skills and education
		 */
		description: () => LocalizedString
	}
	projects: {
		/**
		 * Client Projects
		 */
		client: () => LocalizedString
		/**
		 * Hobby Projects
		 */
		hobby: () => LocalizedString
		/**
		 * Projects
		 */
		projects: () => LocalizedString
		/**
		 * Personal and professional projects I have been part of during my career.
		 */
		description: () => LocalizedString
	}
	publications: {
		/**
		 * Publications
		 */
		publications: () => LocalizedString
		/**
		 * Papers written by me or by a team I have been part of.
		 */
		description: () => LocalizedString
	}
	presentations: {
		/**
		 * Presentations
		 */
		presentations: () => LocalizedString
		/**
		 * Presentations I have given at different events
		 */
		descriptions: () => LocalizedString
	}
	blogs: {
		/**
		 * Blogs
		 */
		blogs: () => LocalizedString
		/**
		 * Blogs I have written
		 */
		description: () => LocalizedString
		/**
		 * Professional blogs
		 */
		professional: () => LocalizedString
		/**
		 * Personal blogs
		 */
		hobby: () => LocalizedString
	}
	cv: {
		/**
		 * Download PDF
		 */
		downloadPDF: () => LocalizedString
		/**
		 * Tuomas Rinne
		 */
		name: () => LocalizedString
		/**
		 * Software Engineer
		 */
		title: () => LocalizedString
		/**
		 * Website
		 */
		website: () => LocalizedString
		/**
		 * Github
		 */
		github: () => LocalizedString
		/**
		 * LinkedIn
		 */
		linkedin: () => LocalizedString
		/**
		 * Summary
		 */
		summary: () => LocalizedString
		/**
		 * I have been working as a software engineer for 6 years in multitude of project from firmware development on embedded systems to complex web applications with multiple different services. I have worked as part of a team and as a lead developer and while my strengths are on the technical side, I also often work directly with clients to understand requirements and communicate progress.
		 */
		summaryText: () => LocalizedString
		/**
		 * Experience
		 */
		experience: () => LocalizedString
		/**
		 * Full Stack Developer, Co-founder, Board member
		 */
		experienceTitle1: () => LocalizedString
		/**
		 * Kvanttori Oy
		 */
		experienceCompany1: () => LocalizedString
		/**
		 * Turku, Finland
		 */
		experienceLocation1: () => LocalizedString
		/**
		 * 2021 - Present
		 */
		experienceDate1: () => LocalizedString
		/**
		 * Lead developer in multiple projects
		 */
		experienceDesc1_1: () => LocalizedString
		/**
		 * Working with multiple tech stacks on different customer projects
		 */
		experienceDesc1_2: () => LocalizedString
		/**
		 * Trainee, Technology
		 */
		experienceTitle2: () => LocalizedString
		/**
		 * Oras Oy
		 */
		experienceCompany2: () => LocalizedString
		/**
		 * Rauma, Finland
		 */
		experienceLocation2: () => LocalizedString
		/**
		 * 2020 - 2021
		 */
		experienceDate2: () => LocalizedString
		/**
		 * Responsible for developing sensor firmware on products used by customers
		 */
		experienceDesc2_1: () => LocalizedString
		/**
		 * Building prototypes for upcoming products
		 */
		experienceDesc2_2: () => LocalizedString
		/**
		 * Education
		 */
		education: () => LocalizedString
		/**
		 * Master of Science (Technology)
		 */
		educationDegree1: () => LocalizedString
		/**
		 * University of Turku
		 */
		educationInstitution1: () => LocalizedString
		/**
		 * Turku, Finland
		 */
		educationLocation1: () => LocalizedString
		/**
		 * 2020 - 2025
		 */
		educationDate1: () => LocalizedString
		/**
		 * Languages
		 */
		languages: () => LocalizedString
		/**
		 * Finnish
		 */
		language1: () => LocalizedString
		/**
		 * English
		 */
		language2: () => LocalizedString
		/**
		 * Skills
		 */
		skills: () => LocalizedString
		/**
		 * Programming Languages
		 */
		programmingLanguages: () => LocalizedString
		/**
		 * Frameworks
		 */
		frameworks: () => LocalizedString
		/**
		 * Databases
		 */
		databases: () => LocalizedString
		/**
		 * Hosting
		 */
		hosting: () => LocalizedString
	}
}

export type Formatters = {}
